Stub font files
Prevent transformation errors in ttf files like:

```
/node_modules/@expo/vector-icons/fonts/Ionicons.ttf:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){

    SyntaxError: Invalid or unexpected token
```